"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Boxes, Check, Loader2, Scale, Tag } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type ListingDraft = { title?:string; condition?:string; included?:string; description?:string; price?:string; delivery?:string; itemKind?:string; weight?:string; legoSetId?:string|null; legoMinifigureId?:string|null; setNumber?:string; theme?:string; sourceAssetId?:string; atlasLow?:number|null; atlasRecommended?:number|null; atlasHigh?:number|null; atlasEvidenceCount?:number|null; atlasBasis?:string|null };
type MinifigureQuote = { status?:string; low?:number|null; recommended?:number|null; high?:number|null; evidenceCount?:number|null; basis?:string|null };
const setStages=["Confirm","Details","Delivery","Preview"];
const looseStages=["Price","Delivery","Preview"];
const money=(value:number)=>`R${Math.round(value||0).toLocaleString("en-ZA")}`;

function normaliseCondition(value?:string){const v=(value||"").toLowerCase();if(v.includes("sealed")||v.includes("new"))return "New Sealed";if(v.includes("incomplete")||v.includes("damaged"))return "Used Incomplete";if(v.includes("complete")||v.includes("clean")||v.includes("usable"))return "Used Complete";return "Unknown";}
function isLooseDraft(draft:ListingDraft){return draft.itemKind==="loose"||(draft.itemKind==="mixed-box"&&/loose lego/i.test(draft.title||""));}
function titleIdentity(draft:ListingDraft){if(isLooseDraft(draft))return {setNumber:"BULK",setName:draft.title?.trim()||"Loose LEGO"};const match=(draft.title||"").match(/^\s*([A-Za-z0-9-]+)\s*[·-]\s*(.+)$/);return {setNumber:draft.setNumber||match?.[1]||(draft.itemKind==="minifigure"?"MINIFIG":"ATLAS"),setName:match?.[2]?.trim()||draft.title?.trim()||"LEGO item"};}

export default function AtlasSellPage(){
 const[stage,setStage]=useState(0);const[draft,setDraft]=useState<ListingDraft>({delivery:"Seller ships"});const[atlasPrice,setAtlasPrice]=useState<number|null>(null);const[pricingLoading,setPricingLoading]=useState(false);const[pricingChecked,setPricingChecked]=useState(false);const[ready,setReady]=useState(false);const[signedIn,setSignedIn]=useState(false);const[publishing,setPublishing]=useState(false);const[publishError,setPublishError]=useState("");
 useEffect(()=>{const saved=window.localStorage.getItem("tbx-listing-draft");if(saved)try{const restored=JSON.parse(saved)as ListingDraft;setDraft({delivery:"Seller ships",...restored});const initial=Number(restored.atlasRecommended??restored.price??0);setAtlasPrice(Number.isFinite(initial)&&initial>0?initial:null);}catch{}createClient().auth.getUser().then(({data})=>{setSignedIn(Boolean(data.user));setReady(true);});},[]);
 useEffect(()=>{if(ready)window.localStorage.setItem("tbx-listing-draft",JSON.stringify(draft));},[draft,ready]);
 useEffect(()=>{if(!ready||pricingChecked||draft.itemKind!=="minifigure"||!draft.legoMinifigureId)return;if(draft.atlasRecommended&&draft.atlasRecommended>0){setAtlasPrice(draft.atlasRecommended);if(!draft.price)setDraft(c=>({...c,price:String(c.atlasRecommended??"")}));setPricingChecked(true);return;}const controller=new AbortController();setPricingLoading(true);void(async()=>{try{const supabase=createClient();const{data:figure}=await supabase.from("lego_minifigures").select("catalogue_id").eq("id",draft.legoMinifigureId).maybeSingle();if(!figure?.catalogue_id)return;const response=await fetch(`/api/value/minifigure/${encodeURIComponent(figure.catalogue_id)}?condition=${encodeURIComponent(draft.condition||"Not sure")}`,{signal:controller.signal});const payload=await response.json();if(!response.ok)return;const quote=(payload?.quote??{})as MinifigureQuote;const recommended=Number(quote.recommended??0);if(quote.status!=="available"||!Number.isFinite(recommended)||recommended<=0)return;setAtlasPrice(Math.round(recommended));setDraft(c=>({...c,price:c.price||String(Math.round(recommended)),atlasLow:quote.low??null,atlasRecommended:Math.round(recommended),atlasHigh:quote.high??null,atlasEvidenceCount:quote.evidenceCount??0,atlasBasis:quote.basis??null}));}catch{}finally{if(!controller.signal.aborted){setPricingLoading(false);setPricingChecked(true);}}})();return()=>controller.abort();},[ready,pricingChecked,draft.itemKind,draft.legoMinifigureId,draft.atlasRecommended,draft.condition,draft.price]);
 const loose=isLooseDraft(draft);const stages=loose?looseStages:setStages;const finalStage=stages.length-1;const weightKg=Number(draft.weight||draft.title?.match(/([\d.]+)\s*kg/i)?.[1]||0);const bulkLow=weightKg>0?Math.round(weightKg*150):0;const bulkHigh=weightKg>0?Math.round(weightKg*250):0;const bulkMid=weightKg>0?Math.round(weightKg*200):0;
 const price=Number(draft.price||0),fee=price*.1,payout=Math.max(0,price-fee);function update(field:keyof ListingDraft,value:string){setDraft(c=>({...c,[field]:value}));}
 async function publish(){if(!signedIn){window.location.href=`/sign-in?next=${encodeURIComponent("/sell/atlas?publish=1")}`;return;}if(!draft.title?.trim()||!Number.isFinite(price)||price<=0){setPublishError("Add a valid price before publishing.");return;}setPublishing(true);setPublishError("");try{const supabase=createClient();const{data:authData,error:authError}=await supabase.auth.getUser();if(authError||!authData.user)throw new Error("Your session has expired. Please sign in again.");const identity=titleIdentity(draft);let assetId=draft.sourceAssetId||null;if(assetId){const{data:owned}=await supabase.from("assets").select("id").eq("id",assetId).eq("owner_id",authData.user.id).maybeSingle();if(!owned)assetId=null;}
  if(!assetId){let legoSetId=draft.legoSetId??null;if(!loose&&!legoSetId&&identity.setNumber!=="ATLAS"&&identity.setNumber!=="MINIFIG"){const{data:set}=await supabase.from("lego_sets").select("id").eq("set_number",identity.setNumber).maybeSingle();legoSetId=set?.id??null;}const assetValues={owner_id:authData.user.id,lego_set_id:loose?null:legoSetId,lego_minifigure_id:draft.legoMinifigureId??null,set_number:identity.setNumber,set_name:identity.setName,theme:loose?"Loose LEGO":draft.theme||(draft.itemKind==="minifigure"?"Minifigures":"LEGO"),condition:normaliseCondition(draft.condition),sealed:loose?false:normaliseCondition(draft.condition)==="New Sealed",estimated_value:loose?price:draft.atlasRecommended??price,passport_status:"Draft",is_public:true,lifecycle_status:"listed",notes:draft.description||draft.included||null};const{data:asset,error:assetError}=await supabase.from("assets").insert(assetValues).select("id").single();if(assetError||!asset)throw assetError??new Error("TBX could not create the item record.");assetId=asset.id;}else{const{error}=await supabase.from("assets").update({condition:normaliseCondition(draft.condition),estimated_value:loose?price:draft.atlasRecommended??price,is_public:true,lifecycle_status:"listed"}).eq("id",assetId).eq("owner_id",authData.user.id);if(error)throw error;}
  const listingValues={asset_id:assetId,seller_id:authData.user.id,title:draft.title.trim(),description:draft.description?.trim()||draft.included||null,asking_price:price,currency:"ZAR",status:"Active",published_at:new Date().toISOString(),lifecycle_state:"listed",value_quote:loose?{source:"TBX bulk guide",condition:draft.condition||"Not sure",delivery:draft.delivery||"Seller ships",weightKg:weightKg||null,low:bulkLow||null,recommended:bulkMid||null,high:bulkHigh||null,basis:"Provisional loose LEGO guide of R150–R250 per kg"}:{source:"Atlas",condition:draft.condition||"Not sure",delivery:draft.delivery||"Seller ships",low:draft.atlasLow??null,recommended:draft.atlasRecommended??null,high:draft.atlasHigh??null,evidenceCount:draft.atlasEvidenceCount??null,basis:draft.atlasBasis??null}};const{data:existing}=await supabase.from("listings").select("id").eq("asset_id",assetId).in("status",["Draft","Active"]).limit(1).maybeSingle();const request=existing?supabase.from("listings").update(listingValues).eq("id",existing.id).select("id").single():supabase.from("listings").insert(listingValues).select("id").single();const{data:listing,error:listingError}=await request;if(listingError||!listing)throw listingError??new Error("TBX could not publish the listing.");window.localStorage.removeItem("tbx-listing-draft");window.localStorage.removeItem("tbx-listing-ready-to-publish");window.location.href=`/marketplace/${listing.id}`;}catch(error){setPublishError(error instanceof Error?error.message:"TBX could not publish this listing. Please try again.");setPublishing(false);}}
 const canContinue=stage!==0||Boolean(draft.title?.trim()&&price>0);
 return <main className="min-h-screen bg-[#050912] text-white"><header className="border-b border-white/[0.06]"><div className="mx-auto flex h-20 max-w-[980px] items-center justify-between px-5 lg:px-10"><Link href="/" className="flex items-center gap-3 font-black"><span className="grid h-10 w-10 place-items-center rounded-xl border border-emerald-400/25 bg-[#09101d] text-emerald-300"><Boxes className="h-5 w-5"/></span>TBX</Link><Link href="/value" className="inline-flex items-center gap-2 text-sm font-bold text-white/55"><ArrowLeft className="h-4 w-4"/> Start over</Link></div></header><section className="mx-auto max-w-[900px] px-4 py-7 sm:px-5 sm:py-10 lg:px-10"><div className="mb-6 flex items-center gap-2">{stages.map((label,index)=><div key={label} className="flex flex-1 items-center gap-2"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-black ${index<=stage?"bg-emerald-400 text-[#050912]":"bg-white/[0.07] text-white/30"}`}>{index+1}</span><span className={`hidden text-xs font-bold sm:block ${index<=stage?"text-white/75":"text-white/25"}`}>{label}</span>{index<stages.length-1?<span className="h-px flex-1 bg-white/10"/>:null}</div>)}</div><div className="rounded-[1.75rem] border border-emerald-400/15 bg-[#09111f] p-5 sm:p-8">
 {stage===0&&loose?<div><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-300"><Scale className="h-6 w-6"/></span><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Loose LEGO</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Set your selling price</h1><p className="mt-2 text-sm text-white/45">Your weight and condition are already saved. Choose the total price you want to list at.</p></div></div><div className="mt-6 rounded-2xl border border-emerald-400/15 bg-emerald-400/[0.045] p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Your loose LEGO</p><h2 className="mt-2 text-2xl font-black">{draft.title||"Loose LEGO"}</h2><p className="mt-2 text-sm text-white/45">{draft.condition||"Condition not specified"}</p></div><div className="mt-6 border-t border-white/[0.07] pt-6"><div className="flex items-center gap-2"><Tag className="h-5 w-5 text-emerald-300"/><h2 className="text-2xl font-black">Price</h2></div>{weightKg>0?<div className="mt-3 rounded-xl border border-white/10 bg-[#050912] p-4"><p className="text-sm leading-6 text-white/55">TBX currently uses a <strong className="text-white">provisional bulk guide of R150–R250/kg</strong>.</p><p className="mt-1 text-sm text-white/45">{weightKg} kg gives a guide of <strong className="text-white">{money(bulkLow)}–{money(bulkHigh)}</strong>. The midpoint is {money(bulkMid)} (R200/kg).</p></div>:null}<label className="mt-5 block"><span className="text-sm font-bold text-white/65">Your total price (ZAR)</span><div className="mt-2 flex h-16 items-center rounded-2xl border border-white/10 bg-[#050912] px-4"><span className="mr-2 text-xl font-black text-white/35">R</span><input type="number" min="0" value={draft.price||""} onChange={e=>update("price",e.target.value)} className="h-full min-w-0 flex-1 bg-transparent text-2xl font-black outline-none"/><span className="text-xs font-bold text-white/30">ZAR</span></div></label></div>{price>0?<div className="mt-5 grid gap-3 sm:grid-cols-3"><Summary label="Asking price" value={money(price)}/><Summary label="TBX fee (10%)" value={`-${money(fee)}`}/><Summary label="Estimated payout" value={money(payout)} highlight/></div>:null}</div>:null}
 {stage===0&&!loose?<div><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-300"><Check className="h-6 w-6"/></span><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Atlas result</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">We found your set!</h1><p className="mt-2 text-sm text-white/45">Atlas has identified your LEGO item.</p></div></div><div className="mt-6 rounded-2xl border border-emerald-400/15 bg-emerald-400/[0.045] p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Match confirmed</p><h2 className="mt-2 text-2xl font-black">{draft.title||"LEGO item"}</h2><p className="mt-2 text-sm text-white/45">{draft.condition||"Condition not specified"}</p></div><div className="mt-6 border-t border-white/[0.07] pt-6"><div className="flex items-center gap-2"><Tag className="h-5 w-5 text-emerald-300"/><h2 className="text-2xl font-black">Set your price</h2></div>{pricingLoading?<p className="mt-3 flex items-center gap-2 text-sm text-white/45"><Loader2 className="h-4 w-4 animate-spin"/> Checking for a suggested price…</p>:atlasPrice?<p className="mt-2 text-sm leading-6 text-white/45">Atlas suggests <strong className="text-white">{money(atlasPrice)}</strong>. Use it or choose the price that works for you.</p>:<p className="mt-2 text-sm leading-6 text-white/45">Choose a fair price that works for you.</p>}<label className="mt-5 block"><span className="text-sm font-bold text-white/65">Your price (ZAR)</span><div className="mt-2 flex h-16 items-center rounded-2xl border border-white/10 bg-[#050912] px-4"><span className="mr-2 text-xl font-black text-white/35">R</span><input type="number" min="0" value={draft.price||""} onChange={e=>update("price",e.target.value)} className="h-full min-w-0 flex-1 bg-transparent text-2xl font-black outline-none"/><span className="text-xs font-bold text-white/30">ZAR</span></div></label></div>{price>0?<div className="mt-5 grid gap-3 sm:grid-cols-3"><Summary label="Asking price" value={money(price)}/><Summary label="TBX fee (10%)" value={`-${money(fee)}`}/><Summary label="Estimated payout" value={money(payout)} highlight/></div>:null}</div>:null}
 {!loose&&stage===1?<div><h1 className="text-3xl font-black">Quick check</h1><p className="mt-3 text-white/45">Atlas already knows the item. Confirm the condition and continue.</p><label className="mt-6 block"><span className="text-sm font-bold text-white/65">Condition</span><select value={draft.condition||"Not sure"} onChange={e=>update("condition",e.target.value)} className="mt-2 h-14 w-full rounded-xl border border-white/10 bg-[#050912] px-4"><option>Not sure</option><option>New / sealed</option><option>Complete used</option><option>Incomplete</option></select></label></div>:null}
 {((loose&&stage===1)||(!loose&&stage===2))?<div><h1 className="text-3xl font-black">How should the buyer receive it?</h1><select value={draft.delivery||"Seller ships"} onChange={e=>update("delivery",e.target.value)} className="mt-6 h-14 w-full rounded-xl border border-white/10 bg-[#050912] px-4"><option>Seller ships</option><option>Collection only</option><option>TBX-managed delivery</option></select></div>:null}
 {((loose&&stage===2)||(!loose&&stage===3))?<div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Listing preview</p><h1 className="mt-3 text-3xl font-black">{draft.title||"Atlas item"}</h1><p className="mt-2 text-white/45">{draft.condition}</p><p className="mt-5 text-4xl font-black text-emerald-300">{money(price)}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><Summary label={loose?"Pricing basis":"Identified by"} value={loose?(weightKg>0?`${weightKg} kg bulk guide`:"Loose LEGO"):"Atlas"}/><Summary label="Delivery" value={draft.delivery||"Seller ships"}/><Summary label="Estimated payout" value={money(payout)} highlight/></div></div>:null}
 {publishError?<p className="mt-5 rounded-xl border border-red-400/20 bg-red-400/[0.08] px-4 py-3 text-sm text-red-200">{publishError}</p>:null}<div className="mt-7 flex items-center justify-between gap-3 border-t border-white/[0.07] pt-5">{stage===0?<Link href="/value" className="px-2 py-3 text-sm font-bold text-white/45">Start over</Link>:<button type="button" onClick={()=>setStage(v=>Math.max(0,v-1))} className="rounded-xl border border-white/10 px-5 py-3 font-bold">Back</button>}{stage<finalStage?<button type="button" disabled={!canContinue} onClick={()=>setStage(v=>Math.min(finalStage,v+1))} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-400 px-6 py-3 font-black text-[#050912] disabled:opacity-40 sm:flex-none">{stage===0?(loose?"Continue to delivery":"Continue to listing"):"Continue"}<ArrowRight className="h-4 w-4"/></button>:<button type="button" disabled={!ready||publishing} onClick={publish} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-400 px-6 py-3 font-black text-[#050912] disabled:opacity-40 sm:flex-none">{publishing?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}{publishing?"Publishing…":signedIn?"Publish listing":"Sign in to publish"}</button>}</div></div></section></main>;
}
function Summary({label,value,highlight=false}:{label:string;value:string;highlight?:boolean}){return <div className={`rounded-2xl border p-4 ${highlight?"border-emerald-400/25 bg-emerald-400/[0.07]":"border-white/10 bg-white/[0.025]"}`}><p className="text-xs text-white/35">{label}</p><p className={`mt-2 font-black ${highlight?"text-emerald-300":"text-white"}`}>{value}</p></div>}
